### ISSUE TITLE
Zoplicate dialog box unreadable in 7.1-beta.12

### ISSUE THREAD

**Issue by pascaloettli** [ChenglongMa/zoplicate#146]
When the dialog box is triggered, it is unreadable:
![Image](https://github.com/user-attachments/assets/71334a6c-ee02-4252-8bbb-1e92920568b9)

**Comment by ChenglongMa** [comment]
Oh, thanks for your feedback! I'll fix the style problem ASAP :)

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @pascaloettli,

Thanks for your patience! I have fixed this issue in the new version :)
Please let me know if it does not work.

Best regards,
Chenglong

**Comment by pascaloettli** [comment]
Zotero: 7.1-beta.16+90a9c5164 (64-bit)
Zoplicate: 3.0.8

![Image](https://github.com/user-attachments/assets/47966c5e-86d9-46fb-b2e8-2bbaafbee95c)

**Comment by ChenglongMa** [comment]
🤔 Sorry I just tested on Zotero 7.0, not the beta version. I will check and fix it soon.

Thanks!

**Comment by vancleve** [comment]
I'm still seeing this in Zoplicate 3.0.8 on Zotero 7.1-beta.21+4915f1fad.

<img width="1153" alt="Image" src="https://github.com/user-attachments/assets/7efb4586-308d-4991-9505-6c5bfc0d88ae" />

**Comment by ChenglongMa** [comment]
Hi @vancleve,

Thanks for your feedback. I'm quite busy recently, haven't got time to fix it. I'll try to do it ASAP. 

Sorry for the inconvenience!

Best,
Chenglong
